@startuml

actor Оператор
participant MES_UI
participant MES_API
participant Cache
participant MES_DB

== Чиение списка заказов ==

Оператор -> MES_UI: Чиение списка заказов
MES_UI -> MES_API: Чиение списка заказов

alt Данные в кеше
    MES_API -> Cache: Чиение списка заказов
    Cache --> MES_API: Список заказов
else Данных нет в кеше
    MES_API -> MES_DB: Чиение списка заказов с БД
    MES_DB --> MES_API: Список заказов
    MES_API -> Cache: Сохранить список заказов в кеш
end

MES_API --> MES_UI: Список заказов
MES_UI --> Оператор: Отображение списка

== Запись изменения статуса заказа ==

Оператор -> MES_UI: Изменения статуса заказа
MES_UI -> MES_API: Изменения статуса заказа

MES_API -> MES_DB: Изменения статуса заказа
MES_DB --> MES_API: Подтверждение обновления статуса

MES_API -> Cache: Инвалидация кеша
Cache --> MES_API: Подтверждение инвалидации кеша

MES_API --> MES_UI: Подтверждение обновления статуса
MES_UI --> Оператор: Подтверждение обновления статуса

@enduml